### ISSUE TITLE
Encoder path hardcoded.

### ISSUE THREAD

**Issue by amirothman** [mayuelala/FollowYourPose#11]
Hey, thank you for the repo! Really cool.

While trying to get the sample up, I realize that the encoder path is hardcoded `followyourpose/models/unet.py` Line 215:

```python
adapter_weight = torch.load('./checkpoints/pose_encoder.pth')
```

I think I can add a PR to make it so that it be accepted through the OmegaConfig, but before I do that, just wanna ask if in case this is some kinda workaround that I'm not aware about.

Cheers!

**Comment by mayuelala** [comment]
Hi, one suggestion is that you could replace this related path to absolute path. If you think this project is helpful, please feel free to leave a star⭐️⭐️⭐️~
