### ISSUE TITLE
More specific description of the datasets used (LAION-POSE, HDVLIA)

### ISSUE THREAD

**Issue by hanbyel0105** [mayuelala/FollowYourPose#13]
Could you please provide a more specific description of the "LAION-POSE" and "HDVLIA" datasets (e.g., total number of images used, metadata)?

**Comment by mayuelala** [comment]
Hi，thank you for your attention，"LAION-POSE" contains about 220K image-pose pairs and the skeletons are detected by HRNet from LAION-Aesthetics.  "HDVILA"  contains 3.3 million videos in total, which are of high quality and distributed in 15 categories in balance. More Details could be found in [here](https://wandb.ai/iejmac/video2dataset/reports/HDVILA-Download-Report--VmlldzozOTc0OTE4)

If you think this project is helpful, please feel free to leave a star⭐️⭐️⭐️，thank you~
