### ISSUE TITLE
I want to retrain the model, where and how to download hdvila dataset?

### ISSUE THREAD

**Issue by dandingbudanding** [mayuelala/FollowYourPose#18]
I want to retrain the model, where and how to download hdvila dataset?

**Comment by mayuelala** [comment]
thank you for your attention, you could download hdvila dataset in https://github.com/microsoft/XPretrain/tree/main/hd-vila-100m，

**Comment by dandingbudanding** [comment]
I have tried this link,but have no access to youtube,anyways, thaks for your reply.

**Comment by jingli18** [comment]
I can download these videos, but where can I get the transcriptions(caps) for them? Did you manualy construct your "caption_rm2048_train.csv"?

**Comment by ttjjmm** [comment]
> 
This is the caption of each frame

**Comment by jingli18** [comment]
> 

Where can I get those captions?
