### ISSUE TITLE
Other Pose/ Skeletons

### ISSUE THREAD

**Issue by p0mad** [mayuelala/FollowYourPose#19]
Hi
Is there any possibilities to use ohter Poses/Skelton methods like either OSX https://osx-ubody.github.io/ or https://github.com/wholebody3d/wholebody3d

UBody Dataset
UBody is a large-scale Upper-Body dataset with the following annotations:
2D whole-body keypoints

**Comment by mayuelala** [comment]
Sure，I think this is good idea to explore !

**Comment by p0mad** [comment]
@mayuelala 
Thats great, is there any planned schedule to add them?

Thanks
Best regards
