### ISSUE TITLE
What parts of Cross-Frame Attention have been reformed in your project relative to Tune-A-Video？

### ISSUE THREAD

**Issue by XuejiFang** [mayuelala/FollowYourPose#20]
As the author mentioned in Abstract: _In the second stage, we finetune the motion of the above network via a pose-free video dataset by adding the learnable temporal self-attention and **reformed cross-frame self-attention blocks**._

Can I understand the cross-frame attn mentioned in your paper is the SparseCausalAttention Class in your opened-source codes, which is the same as the SparseCausalAttention Class writen in Tune-A-Video? In this case, how does the Cross-Frame Attn reformed in your project? Which part of the code is embodied?

**Comment by mayuelala** [comment]
Yes, It is the same as the SparseCausalAttention Class writen in Tune-A-Video.
We finetune the SCA on HDVILA and add lora to keep consistancy.
As for code, you could find it in [here](https://github.com/mayuelala/FollowYourPose/blob/main/configs/pose_train.yaml#L36)
