### ISSUE TITLE
Fix the bug in multi-gpu training

### ISSUE THREAD

**Issue by Trainingzy** [mayuelala/FollowYourPose#24]
Hi, thanks for your great work!

As for the multi-gpu training bug in Tune-A-Video, may I ask where the bug is?

I compare the training scripts in [this repo](https://github.com/mayuelala/FollowYourPose/blob/main/train_followyourpose.py) and [Tune-A-Video](https://github.com/showlab/Tune-A-Video/blob/main/train_tuneavideo.py). But I do not find the difference.

**Comment by mayuelala** [comment]
Hi, we add the multi-gpu script and fix the optimizer~. 
If you use the codebase from Tune-a-vidoe, you maybe meet the bug that can not launch the multi-gpu

**Comment by Trainingzy** [comment]
Hi, Yes I use the codebase from Tune-A-Video, and meet this problem. So my question is how to modify the code to make it work... 

As for the optimizer, where do u change? I cannot find the different part
