### ISSUE TITLE
No such file or directory: 'Your dataset path/caption_rm2048_train.csv'

### ISSUE THREAD

**Issue by Lionelding** [mayuelala/FollowYourPose#28]
Same issue for caption_rm2048_train.csv, it is not available in https://github.com/microsoft/XPretrain/tree/main/hd-vila or https://github.com/microsoft/XPretrain/tree/main/hd-vila-100m.
Could you please point me to the place where you found it?
Appreciate your help

**Comment by mayuelala** [comment]
Sorry, don't need to repeat your question,  as for caption_rm2048_train.csv, we applied server dataset which was downloaded several months ago.  please give me your email, I will send it to you.

**Comment by KaustubhPatange** [comment]
@mayuelala Can I get the dataset as well, here is my email developerkp16@gmail.com?
