### ISSUE TITLE
RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?

### ISSUE THREAD

**Issue by treesturn** [mayuelala/FollowYourPose#37]
Hi, i tried running the training code and inference code but i kept recieving these errors

![image](https://github.com/mayuelala/FollowYourPose/assets/77474648/8de59b90-ce8d-4382-a4cd-3b25615c6bfe)

**Comment by mayuelala** [comment]
which GPU are you using ? We test the Xformer on A100 and 3090 and provide the package

**Comment by treesturn** [comment]
@mayuelala Im using a 2060

**Comment by mayuelala** [comment]
as for 2060, may be you need to rebuild the xformer following the official instruction
