### ISSUE TITLE
How to obtain the pose video? Could you please give the implement details of mmpose and HRNet?

### ISSUE THREAD

**Issue by Francis-Rings** [mayuelala/FollowYourPose#38]
Excellent work! I want to know the implement details of mmpose and HRNet for obtaining the pose video, since your source code don't show the details.

**Comment by mayuelala** [comment]
Thanks for your attention, maybe you could use the [mmpose](https://mmpose.readthedocs.io/en/latest/demos.html#d-human-pose-bottom-up-image-video-demo), remember to replace background to black.

<img width="1378" alt="图片" src="https://github.com/mayuelala/FollowYourPose/assets/38033523/c6429f5b-2109-4352-b5ee-9bcdb189852b">
