### ISSUE TITLE
Plan to support new version of diffusers?

### ISSUE THREAD

**Issue by ashleyng7078** [mayuelala/FollowYourPose#42]
Hello, I would like to personalize the origin model SD1.4 with dreambooth and integrate with your pipeline for inference. However, I use the latest version of diffusers to train Dreambooth. Therefore, when loading the model, I encounter this error:

> ValueError: unknown mid_block_type : UNetMidBlock2DCrossAttn

Would you please help me with this error?

**Comment by mayuelala** [comment]
Sure, may you need to install the diffuser==0.11.1
