### ISSUE TITLE
No such file or directory: 'Your dataset path/caption_rm2048_train.csv'

### ISSUE THREAD

**Issue by Meg-R** [mayuelala/FollowYourPose#43]
Hi,

could you send me the csv files that are needed? I can't find it anywhere. thanks

**Comment by mayuelala** [comment]
thanks for your attention
could you please give me a email address， I will send it

**Comment by mayuelala** [comment]
https://drive.google.com/file/d/14cswUM85IwmWCIcALXHDo-cQpLLukX39/view?usp=share_link
