### ISSUE TITLE
No such file or directory: 'Your dataset path/caption_rm2048_train.csv'

### ISSUE THREAD

**Issue by KWLuna** [mayuelala/FollowYourPose#44]
Duplicated Issue of: https://github.com/mayuelala/FollowYourPose/issues/26#issue-1848837203

I would like to request for dataset that has been used in this project.

**Comment by mayuelala** [comment]
thanks for your attention
could you please give me a email address， I will send it

**Comment by mayuelala** [comment]
https://drive.google.com/file/d/14cswUM85IwmWCIcALXHDo-cQpLLukX39/view?usp=share_link
