### ISSUE TITLE
how to enhance the generation quality?

### ISSUE THREAD

**Issue by vicemm1** [mayuelala/FollowYourPose#48]
Hello, I've been using your project for action video generation. I conducted experiments on a V100-32G GPU, inputting a skeleton video of around seven seconds and trying various prompts. However, the generated results didn't quite meet the showcased effects. I'm wondering, without shortening the video length, which parameters can be modified to enhance the generation quality?

**Comment by mayuelala** [comment]
we will release new version codebase as soon as possible

**Comment by vicemm1** [comment]
That‘s great！thanks for your reply。 Best regards！
