### ISSUE TITLE
when to release the whole training code and data

### ISSUE THREAD

**Issue by gallenszl** [mayuelala/FollowYourPose#49]
Hello, as the paper has been accepted, did you have plan to release the whole training code and data?

**Comment by mayuelala** [comment]
thanks for attention, we are trying to to do it

**Comment by rohit901** [comment]
any updates on this? @mayuelala

**Comment by gallenszl** [comment]
> any updates on this? @mayuelala

same question

**Comment by johndpope** [comment]
This other repo has training code - maybe helpful https://github.com/MooreThreads/Moore-AnimateAnyone/

**Comment by rohit901** [comment]
yeah its a good repo, and the only open source repo with training code right now I guess..

**Comment by mayuelala** [comment]
hi，everyone， we have release the training code. As for dataset,  we are cleaning them. I recommend to use other datasets such as human-sd

**Comment by rohit901** [comment]
Thank you for releasing this code!
