### ISSUE TITLE
pose video

### ISSUE THREAD

**Issue by Beiyuan-Zhang** [mayuelala/FollowYourPose#50]
Hi, can you elaborate on the production process of pose video, Why do I always make videos with mmpose with key points， thank you

**Comment by mayuelala** [comment]
thank you for your attention， you can refer our issue [here](https://github.com/mayuelala/FollowYourPose/issues/38) , if you have any trouble, let me know. please star this project, thanks ~

**Comment by Beiyuan-Zhang** [comment]
OK，I star this project， it's really perfect! But how can i replace background to black，it seems not having this option
![1](https://github.com/mayuelala/FollowYourPose/assets/75128462/17152cde-9236-49f0-a49a-a50f3d917ebe)

**Comment by mayuelala** [comment]
thanks, you need to init a same size tensor with input image. like this:
`background = torch.zeros_like(image)`
The mmpose doesn't support to black ground by option.

**Comment by Beiyuan-Zhang** [comment]
OK, I solved it, thank you bro！

**Comment by Beiyuan-Zhang** [comment]
Hi, I put my pose video into the code, but I met an error 
IndexError: Out of bound indices: [ 65  70  75  80  85  90  95 100 105 110 115 120 125 130 135 140 145 150 155]，
have you met this problem? or do you have any idea with this?
this is my video

https://github.com/mayuelala/FollowYourPose/assets/75128462/e17be06d-e22b-4b13-b591-dc9aa94c38e5

**Comment by mayuelala** [comment]
firstly, the color of skeleton is totally different

**Comment by Beiyuan-Zhang** [comment]
yeah，you are right, but why? the head and body is also blue in this pic
![image](https://github.com/mayuelala/FollowYourPose/assets/75128462/af24c3c9-57a2-4c0b-8eee-aa2da70e0fa9)

**Comment by mayuelala** [comment]
maybe you can check your visual code~ you also need to notice the length of sketch video and sample stride, if you have any other problem, let me know

**Comment by Beiyuan-Zhang** [comment]
It worked! Really thank you!

**Comment by mayuelala** [comment]
if you have any other problem, you can add me wechat: Marlin_Sagittarius

**Comment by ltttpku** [comment]
refine it: hi, may I ask where to add code for replacing the background with black?

**Comment by ltttpku** [comment]
hi, may I ask where to add code for replacing the background with black?

**Comment by Beiyuan-Zhang** [comment]
yeah, maybe you can debug the source code in mmpose, and find where to generate the image

**Comment by Kebii** [comment]
> yeah，you are right, but why? the head and body is also blue in this pic ![image](https://private-user-images.githubusercontent.com/75128462/292215921-af24c3c9-57a2-4c0b-8eee-aa2da70e0fa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzc2MTEsIm5iZiI6MTcxNzAzNzMxMSwicGF0aCI6Ii83NTEyODQ2Mi8yOTIyMTU5MjEtYWYyNGMzYzktNTdhMi00YzBiLThlZWUtYWEyZGE3MGUwZmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAyNDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYjQwZTFkNGQ3OTMwYzc4OWVjMmRhNTVjZTRiZWY5MGNlMTFlYTMyZGRmMDY1ZThlOWRhNTY2OTY0Njc5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VTR9qvBR0d6V1qjjLZskBpV1ln7z7lWk4yUplizTNLo)

I meet the same problem. The color map of the mmpose is different from the demo of this repo. Do you know how I can solve it?
