### ISSUE TITLE
How to make pose video?

### ISSUE THREAD

**Issue by arijin** [mayuelala/FollowYourPose#8]
I want make the pose video like the mov in pose_example. What tool should i use?

**Comment by mayuelala** [comment]
Hi，You could make the pose video by mmpose，the url is [mmpose](https://github.com/open-mmlab/mmpose) , we detect the skeleton by HRNet[1].  You just need to run the video demo to obtain the pose video.  Remember to replace the background with black.

To facilitate sampling, we are going to integrate the skeleton detector into FollowYourPose, stay tuned !

[1] Ke Sun, Bin Xiao, Dong Liu, and Jingdong Wang. Hrnet: Deep high-resolution representation learning for human pose estimation. In Proceedings of the IEEE/CVF Conference

**Comment by amirothman** [comment]
> Remember to replace the background with black.

How does one achieve this?

**Comment by vinthony** [comment]
you may need the tools from here: https://huggingface.co/spaces/fffiloni/video2mmpose
