### ISSUE TITLE
SD Auto's 1111 Ui Extension ? 

### ISSUE THREAD

**Issue by Kamekos** [mayuelala/FollowYourPose#9]
The project looks really promising so far ! 
But sadly I'm not able to make it work on the hugginface demo, are you planning on releasing an extension for Auto's UI ?

**Comment by mayuelala** [comment]
Sure， we are doing this！Now you need to input the skeleton video on the hugginface demo

**Comment by mayuelala** [comment]
<img width="1365" alt="图片" src="https://user-images.githubusercontent.com/38033523/230719227-13d86a6e-0c2f-4aeb-be74-a81412aba212.png">

**Comment by mayuelala** [comment]
If you think this project is helpful, please feel free to leave a star⭐️⭐️⭐️ ~
